name: Request YouTube Trend API
on:
  workflow_dispatch:
  schedule:
    - cron:  "00 17 * * *"

jobs:
  build:
    name: Collect YouTube Trends
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}

    steps:
      - uses: actions/checkout@v3

      # Setup Python and install dependencies
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8.15"
      - run: pip install -r requirements.txt
      - name: Create data folder
        run: mkdir -p data

      # Setup Workload Identity Federation
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}

      - name: Collect YouTube Trends
        run: python yt_trends_mining/trends.py
      
      # Upload files to Google Cloud Storage
      - id: 'upload-file'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: 'data'
          destination: 'yt-trends-mining'
